name: EuroTravelTranslate
options:
  bundleIdPrefix: com.minasehiro
  deploymentTarget:
    iOS: "26.0"
  xcodeVersion: "26.0"

settings:
  base:
    SWIFT_VERSION: "6.0"
    IPHONEOS_DEPLOYMENT_TARGET: "26.0"
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: "7N5L874449"

targets:
  EuroTravelTranslate:
    type: application
    platform: iOS
    sources:
      - path: EuroTravelTranslate
      - path: Resources
        type: group
        buildPhase: resources
    settings:
      base:
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight UIInterfaceOrientationPortraitUpsideDown"
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_CFBundleDisplayName: "Euro Travel Utility"
        PRODUCT_BUNDLE_IDENTIFIER: com.minasehiro.EuroTravelTranslate
        INFOPLIST_KEY_NSLocationWhenInUseUsageDescription: "近くのお店や施設の種類から、支出カテゴリを自動で推測します"
        MARKETING_VERSION: "2.0.0"
        CURRENT_PROJECT_VERSION: 1

  EuroTravelTranslateTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: EuroTravelTranslateTests
    dependencies:
      - target: EuroTravelTranslate
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/EuroTravelTranslate.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/EuroTravelTranslate"
        BUNDLE_LOADER: "$(TEST_HOST)"
