devices([
  "iPhone 17 Pro Max",
  "iPhone 16e",
])

languages(["ja"])

scheme("EuroTravelTranslateUITests")
output_directory("./fastlane/screenshots")

clear_previous_screenshots(true)
override_status_bar(true)
